test/integration_test.go
Prior to this commit `woodpeckerRun` let a woodpecker instance under
test run for _exactly_ the time required to do a fixed number of
monitoring iterations based on the configured STH fetch interval. In
practice we can't expect the monitors to complete in exactly that amount
of time every time. This commit oversleeps for 20ms to ensure that minor
scheduling differences in the monitor goroutines don't cause the test to
fail. This resolves the failures where the monitor was killed early and
did not complete its expected work. Running integration tests in a tight
loop locally with this fix applied showed no failures.
Unfortunately the above is not enough to fix all CI failures and so this
commit also loosens the `sth_latency_count` and expected number of STH
fetch tests to accept …
=> integration: allow for some padding in woodpeckerRun.

monitor/cert_submitter.go, monitor/cert_submitter_test.go, monitor/monitor.go, monitor/monitor_test.go, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, pki/certs.go, pki/certs_test.go, pki/io_test.go, test/integration_test.go, test/io.go, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
This commit introduces support for periodically submitting precerts as
well as (or in place of) final certificates.
Some general cleanup, refactoring & test coverage improvement is
included as well. This includes fixing the flakyness on master (by
ensuring we wait for the cttestsrv instances to come up before
proceeding with the woodpecker run).
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/21
=> Monitor: Support submitting precerts.

monitor/cert_submitter.go, monitor/cert_submitter_test.go, monitor/monitor.go, monitor/monitor_test.go, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, test/config.json, test/cttestsrv/server.go, test/integration_test.go, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
Previously, each log's monitor's `STHFetcher` or
`CertSubmitter` would block on the STH fetch or cert submission
completing or timing out, sleep for the cycle duration, and then repeat.
The problem with this approach is that if a log has high latency the
monitoring schedule will gradually skew and we end up performing fewer
STH fetches/cert submissions than intended.
This commit updates the `certSubmitter` and `sthFetcher` to perform the
STH fetching and cert submission in separate goroutines. This ensures
that every cycle tries to perform its work even if the work ends up
lagging.
Along the way I exposed the timeout for both STH fetching and cert
submission back through the configuration layers to allow setting
a sensible timeout for both operations per-log.
Similarly, I updated the …
=> Process STH fetching and (pre)cert submission async.

Makefile, util/config.dist.json, util/ct-woodpecker.service
This commit adds a Makefile with an `install` PHONY target that will (if required):
1) Build `ct-woodpecker`
2) Create a `woodpecker` user with no home directory or shell access
3) Create a `/etc/ct-woodpecker` configuration dir
4) Populate `/etc/ct-woodpecker/config.json`,
`/etc/ct-woodpecker/issuer.pem`, and `/etc/ct-woodpecker/issuer.key`
with defaults
5) Install, enabled, and start a systemd unit for a simple
`ct-woodpecker` service that runs `ct-woodpecker` as `woodpecker`
with the `/etc/ct-woodpecker/config.json` configuration.
This is sufficient for a dead simple Linux-focused production install of
`ct-woodpecker`.
Resolves #15
=> Add systemd unit & makefile.

Makefile
Run adduser before chown, to prevent an error about user not existing.
Use restart instead of start so command will work when repeated.
=> Deployment tweaks.

monitor/cert_submitter.go, monitor/sth_fetcher.go
We always want to fetch an STH or submit certificates immediately after
startup before sleeping.
=> Monitor: Always do a cycle at startup before sleeping.

monitor/cert_submitter.go, monitor/monitor.go, monitor/monitor_test.go, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, test/integration_test.go, test/metrics.go
_Note to reviewers: This branch doesn't have an integration test.
I think it should but wanted to get some :mag: input before I was
OOO for Canada day_
After fetching more than one STH the monitor will now verify the
consistency between the current STH and the previously observed STH.
Errors are tracked in the Prometheus `sth_inconsistencies` counter vec
sliced by the log URI and the type of inconsistency (bad STHs, failure
to get a consistency proof, failure to validate the consistency proof).
The latency of fetching a STH consistency proof is tracked in the
Prometheus `sth_proof_latency` histogram.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/4
=> STH Fetcher: Verify consistency between STHs.

monitor/cert_submitter.go
When the `certSubmitter` has storage configured it tries to serialize the
SCT from cert submissions to store in the storage using `cttls.Marshal`.
This means we must dereference the `*ct.SignedCertificateTimestamp`
to use it as an argument for marshaling, otherwise it will error. This
commit adds the required deref.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/46
=> cert-submitter: fix SCT serialization error.

.gitignore, test/config.json, util/config.dist.json, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
`woodpecker.New` now supports providing `inclusionChecker` options and
a storage `DBURI`. This allows the command line `ct-woodpcker` to use
the `inclusionChecker`. The included example config files are updated to
use both features. The `.gitignore` is updated to ignore the default
suggested database file.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/42
=> woodpecker: wire up certificate inclusion checker.

monitor/inclusion_checker.go, monitor/inclusion_checker_test.go
The second argument to `getEntries` is inclusive. When fetching to the
current treesize we need to fetch the entries up to treesize - 1.
Similarly, when looping we need to exit when start == end, meaning the
loop should run when start < end, not start <= end.
=> inclusion-checker: fix off-by-one error.

monitor/inclusion_checker.go
I found this stat to be useful while I was working on the ct-test-srv and gives a picture of the backlog of unseen certs that are outstanding beyond just knowing the age of the oldest in the backlog.
=> inclusion-checker: add Prometheus gauge for unseen certs

monitor/monitor.go
The `monitor.New` constructor that created the `inclusionChecker` struct
was not wiring through the `opts.InclusionOpts.MaxGetEntries` setting
from the provided inclusion checker configuration. This results in an
OOM condition in `getEntries` when no clipping on the end range is done
and an entire log's worth of entries are built up in a single slice.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/53
=> inclusionChecker: set `MaxGetEntries` from inclusionOptions.

cmd/ct-woodpecker/main.go, monitor/cert_submitter.go, monitor/cert_submitter_test.go, monitor/common.go, monitor/common_test.go, monitor/inclusion_checker.go, monitor/inclusion_checker_test.go, monitor/monitor.go, monitor/monitor_test.go, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, test/integration_test.go, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
The individual check types used by the `monitor` package
(`sthFetcher`, `certSubmitter`, `inclusionChecker`) now embed a common
`monitorChecker` type. This is used to bundle up the common config
parameters used by all the checkers and provide convenience functions
for logging.
There is now a separate logger for stdout/stderr. The `ct-woodpecker`
binary creates these with os.Stderr and os.Stdout. Programmatic users
(e.g. tests) are free to use the same logger for both the stdout and
stderr loggers for simplicity.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/36
=> Separate stdout/stderr, common monitorChecker type.

monitor/common.go, monitor/monitor.go, monitor/monitor_test.go, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, test/config.json, util/config.dist.json, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
If a log gives back a valid STH for a smaller treesize than the previously seen STH (a stale STH) don't overwrite prevSTH and don't check consistency proof. If the stale STH is older than the log's MMD, print an error.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/61
=> Handle stale STHs.

monitor/sth_fetcher.go, monitor/sth_fetcher_test.go, test/cttestsrv/log.go
There's no need to spawn a separate goroutine to verify consistency proofs. This also avoids a datarace when unit tests change the client mock out from under the sthFetcher.
Along the way this also fixes a upstream breakage in the cttestsrv.
=> sthFetcher: Remove debug prints, fix data race

test/cttestsrv/log.go
The upstream Trillian project [refactored the memory storage provider](https://github.com/google/trillian/commit/55141304712f380c1e199caf76fbee1e226cc6b5) and since we don't vendor dependencies this broke the cttestsrv.
=> cttestsrv: fix upstream memory storage API change.

cmd/ct-woodpecker/main.go, monitor/cert_submitter.go, pki/certs_test.go, storage/storage.go, test/cttestsrv/log.go, test/cttestsrv/management_handlers.go, woodpecker/woodpecker.go
This PR addresses the low hanging nits [flagged by GolangCI](https://golangci.com/r/github.com/letsencrypt/ct-woodpecker).
It leaves three "megacheck" findings yet to be addressed in the `cttestsrv`:
* signedLogRoot.TreeSize is deprecated: TreeSize moved to LogRoot.
* signedLogRoot.TimestampNanos is deprecated: TimestampNanos moved to LogRoot.
* signedLogRoot.RootHash is deprecated: RootHash moved to LogRoot.
All of the above are a result of https://github.com/google/trillian/commit/0c12c8487309740c70e2da695f3c8043cb4f11e1 - it looks like the `certificate-transparency-go` ctfe is still using the deprecated fields so I think we can ignore these for now. I _think_ fixing it will require unserializing the `log_root []byte` from the response and that's too fiddly for my low-hanging PR.
=> Fix golangci nits

.travis.yml
Leaving it in causes external PRs to fail because the encrypted COVERALLS_TOKEN env var isn't available and an empty `-repotoken` argument is invalid (See e.g. https://travis-ci.org/letsencrypt/ct-woodpecker/builds/469815134).
We don't need the `-repotoken` at all: it is only useful for private Github repositories.
=> CI: Remove goveralls -repotoken argument.

monitor/inclusion_checker.go, monitor/inclusion_checker_test.go
If tree size is X, the highest value we can have for `end` in
get-entries is X-1.
=> Fix off-by-one error in checkInclusion.

monitor/inclusion_checker.go, monitor/inclusion_checker_test.go, test/config/ct-woodpecker.docker.json, test/config/ct-woodpecker.localdev.json, util/config.dist.json, woodpecker/woodpecker.go, woodpecker/woodpecker_test.go
FetchBatchSize didn't really need to be configurable, since we can
always request a reasonably large size, and logs will give us back the
maximum that they will allow up to that size. Having fewer config options
makes the tool easier to use.
This also adds godoc documenting some config options.
=> Remove FetchBatchSize and update other comments.

README.md, monitor/sth_fetcher.go, monitor/sth_fetcher_test.go
Count total number of get-sth calls that are made to allow for SLO calculations.
=> Add sth_fetch_total metric

woodpecker/woodpecker.go
The existing HTTP server allows exposing Prometheus metrics. To improve  visibility into the Go runtime its helpful to also have access to `pprof` information through this HTTP server.
This PR updates `woodpecker.initMetrics` such that the returned HTTP server will use a `http.ServeMux` that direct metrics requests to the correct Prometheus handlers and `pprof` requests to the `pprof` handlers.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/81
=> woodpecker: add pprof endpoints to metrics server.

test/config/grafana/provisioning/dashboards/dashboard.json
The inclusion checker panels weren't using the `$log` variable to only show data related to the selected log.
Since this is running locally I also changed the default refresh rate to be faster (every 5s instead of every 1m).
=> grafana: tweak grafana docker env dashboard.

examples/config.dist.json, monitor/cert_submitter.go, monitor/cert_submitter_test.go, pki/certs.go, pki/certs_test.go, test/config/ct-woodpecker.localdev.json
Previously the base domain for all the test certificate subjects was
a static string specific to Let's Encrypt. Allowing this base domain to
be configured in the cert submitter config will help outside
organizations use this tool with their own logs.
Resolves https://github.com/letsencrypt/ct-woodpecker/issues/105
=> cert-submitter: allow custom base domain.

.golangci.yaml, .travis.yml
One of the transitive dependencies of `ct-woodpecker` seems to have moved/gone away causing consistent build failures of the form:
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/travis/gopath/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
```
We already vendor dependencies to avoid this sort of problem. The easiest "fix" in this case was to remove a workaround `go mod download` we did to appease earlier `golangci-lint` versions.
In short:
* Updated to Go 1.13 (why not)
* Updated `golangci-lint`
* Removed `go …
=> CI: switch to Go 1.13, update golangci-lint, avoid module download.

.github/workflows/golangci-lint.yml, .github/workflows/test.yml, .golangci.yaml, monitor/sth_fetcher.go, pki/certs.go, pki/certs_test.go, test/cttestsrv/log.go
Change the behavior of the test certificate generation to always create a
90 day certificate, and make sure it falls in the temporal shard window if
one is defined. If issuing a certificate for a current temporal shard
(where the system time + 90d `NotAfter` lands in the temporal window),
then generate a certifcate based on the current time. If generating a
certificate for a past or future temporal shard, then generate a 90d
certificate that falls in that window.
In addition, fix failing CI with updates and lint fixes:
* Update golangci-lint
* Add the ability to run tests and lint manually in GitHub Actions
* Add lint exclusions
* Fix misspelling
* Remove duplicate tls import
Fixes #127
=> Use 90 day test certs in temporal shard window

docker-compose.yml
Let's Encrypt uses percona-xtradb-cluster as the database backend for ct-woodpecker. Upgrade from mariadb 10.3 to the latest percona-server version.
=> Update container mariadb to percona-server 8.0

README.md
These status badges are not super useful at best, and broken at worst.
=> Remove status badges from README.md
